FROM golang:1.19-alpine as builder

RUN apk update && apk add make

COPY pkg /workdir/app/pkg
COPY staging /workdir/app/staging
COPY cmd /workdir/app/cmd
COPY vendor /workdir/app/vendor
COPY go.mod /workdir/app/go.mod
COPY go.sum /workdir/app/go.sum
COPY Makefile /workdir/app/Makefile

WORKDIR /workdir/app

RUN make marooned_shim

FROM alpine:3.18
COPY --from=builder /workdir/app/marooned_shim /app/marooned_shim
WORKDIR /app
ENTRYPOINT ["/app/marooned_shim"]
