FROM golang:1.19-alpine as builder

RUN apk update && apk add make

COPY pkg /workdir/app/pkg
COPY staging /workdir/app/staging
COPY cmd /workdir/app/cmd
COPY vendor /workdir/app/vendor
COPY go.mod /workdir/app/go.mod
COPY go.sum /workdir/app/go.sum
COPY Makefile /workdir/app/Makefile

WORKDIR /workdir/app

RUN make marooned_shim marooned_oci

FROM alpine:3.18
COPY --from=builder /workdir/app/marooned_shim /app/marooned_shim
COPY --from=builder /workdir/app/marooned_oci /app/marooned-oci
COPY cmd/marooned-shim/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh /app/marooned-oci
WORKDIR /app
ENTRYPOINT ["/app/entrypoint.sh"]
