//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The MaroonedPods Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertConfig) DeepCopyInto(out *CertConfig) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RenewBefore != nil {
		in, out := &in.RenewBefore, &out.RenewBefore
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertConfig.
func (in *CertConfig) DeepCopy() *CertConfig {
	if in == nil {
		return nil
	}
	out := new(CertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaroonedPods) DeepCopyInto(out *MaroonedPods) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaroonedPods.
func (in *MaroonedPods) DeepCopy() *MaroonedPods {
	if in == nil {
		return nil
	}
	out := new(MaroonedPods)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaroonedPods) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaroonedPodsCertConfig) DeepCopyInto(out *MaroonedPodsCertConfig) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(CertConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(CertConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaroonedPodsCertConfig.
func (in *MaroonedPodsCertConfig) DeepCopy() *MaroonedPodsCertConfig {
	if in == nil {
		return nil
	}
	out := new(MaroonedPodsCertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaroonedPodsConfig) DeepCopyInto(out *MaroonedPodsConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaroonedPodsConfig.
func (in *MaroonedPodsConfig) DeepCopy() *MaroonedPodsConfig {
	if in == nil {
		return nil
	}
	out := new(MaroonedPodsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaroonedPodsConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaroonedPodsConfigList) DeepCopyInto(out *MaroonedPodsConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaroonedPodsConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaroonedPodsConfigList.
func (in *MaroonedPodsConfigList) DeepCopy() *MaroonedPodsConfigList {
	if in == nil {
		return nil
	}
	out := new(MaroonedPodsConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaroonedPodsConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaroonedPodsConfigSpec) DeepCopyInto(out *MaroonedPodsConfigSpec) {
	*out = *in
	out.BaseVMResources = in.BaseVMResources
	if in.Sandbox != nil {
		in, out := &in.Sandbox, &out.Sandbox
		*out = new(SandboxConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceOverhead != nil {
		in, out := &in.ResourceOverhead, &out.ResourceOverhead
		*out = new(corev1.ResourceList)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
			for key, val := range *in {
				(*out)[key] = val.DeepCopy()
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaroonedPodsConfigSpec.
func (in *MaroonedPodsConfigSpec) DeepCopy() *MaroonedPodsConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MaroonedPodsConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaroonedPodsConfigStatus) DeepCopyInto(out *MaroonedPodsConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaroonedPodsConfigStatus.
func (in *MaroonedPodsConfigStatus) DeepCopy() *MaroonedPodsConfigStatus {
	if in == nil {
		return nil
	}
	out := new(MaroonedPodsConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaroonedPodsList) DeepCopyInto(out *MaroonedPodsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaroonedPods, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaroonedPodsList.
func (in *MaroonedPodsList) DeepCopy() *MaroonedPodsList {
	if in == nil {
		return nil
	}
	out := new(MaroonedPodsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaroonedPodsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaroonedPodsSpec) DeepCopyInto(out *MaroonedPodsSpec) {
	*out = *in
	in.Infra.DeepCopyInto(&out.Infra)
	in.Workloads.DeepCopyInto(&out.Workloads)
	if in.CertConfig != nil {
		in, out := &in.CertConfig, &out.CertConfig
		*out = new(MaroonedPodsCertConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PriorityClass != nil {
		in, out := &in.PriorityClass, &out.PriorityClass
		*out = new(MaroonedPodsPriorityClass)
		**out = **in
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaroonedPodsSpec.
func (in *MaroonedPodsSpec) DeepCopy() *MaroonedPodsSpec {
	if in == nil {
		return nil
	}
	out := new(MaroonedPodsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaroonedPodsStatus) DeepCopyInto(out *MaroonedPodsStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaroonedPodsStatus.
func (in *MaroonedPodsStatus) DeepCopy() *MaroonedPodsStatus {
	if in == nil {
		return nil
	}
	out := new(MaroonedPodsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxConfig) DeepCopyInto(out *SandboxConfig) {
	*out = *in
	if in.KernelBoot != nil {
		in, out := &in.KernelBoot, &out.KernelBoot
		*out = new(SandboxKernelBoot)
		**out = **in
	}
	if in.PoolSizeClasses != nil {
		in, out := &in.PoolSizeClasses, &out.PoolSizeClasses
		*out = make([]SandboxSizeClass, len(*in))
		copy(*out, *in)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(SandboxNetwork)
		**out = **in
	}
	if in.PublishGuestIPOnPod != nil {
		in, out := &in.PublishGuestIPOnPod, &out.PublishGuestIPOnPod
		*out = new(bool)
		**out = **in
	}
	if in.ExtraGuestOverhead != nil {
		in, out := &in.ExtraGuestOverhead, &out.ExtraGuestOverhead
		*out = new(corev1.ResourceList)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
			for key, val := range *in {
				(*out)[key] = val.DeepCopy()
			}
		}
	}
	if in.ConfidentialCompute != nil {
		in, out := &in.ConfidentialCompute, &out.ConfidentialCompute
		*out = new(SandboxConfidentialCompute)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxConfig.
func (in *SandboxConfig) DeepCopy() *SandboxConfig {
	if in == nil {
		return nil
	}
	out := new(SandboxConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxConfidentialCompute) DeepCopyInto(out *SandboxConfidentialCompute) {
	*out = *in
	if in.RequireCapableNode != nil {
		in, out := &in.RequireCapableNode, &out.RequireCapableNode
		*out = new(bool)
		**out = **in
	}
	if in.Trustee != nil {
		in, out := &in.Trustee, &out.Trustee
		*out = new(SandboxTrustee)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxConfidentialCompute.
func (in *SandboxConfidentialCompute) DeepCopy() *SandboxConfidentialCompute {
	if in == nil {
		return nil
	}
	out := new(SandboxConfidentialCompute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxKernelBoot) DeepCopyInto(out *SandboxKernelBoot) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxKernelBoot.
func (in *SandboxKernelBoot) DeepCopy() *SandboxKernelBoot {
	if in == nil {
		return nil
	}
	out := new(SandboxKernelBoot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxNetwork) DeepCopyInto(out *SandboxNetwork) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxNetwork.
func (in *SandboxNetwork) DeepCopy() *SandboxNetwork {
	if in == nil {
		return nil
	}
	out := new(SandboxNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSizeClass) DeepCopyInto(out *SandboxSizeClass) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSizeClass.
func (in *SandboxSizeClass) DeepCopy() *SandboxSizeClass {
	if in == nil {
		return nil
	}
	out := new(SandboxSizeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxTrustee) DeepCopyInto(out *SandboxTrustee) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxTrustee.
func (in *SandboxTrustee) DeepCopy() *SandboxTrustee {
	if in == nil {
		return nil
	}
	out := new(SandboxTrustee)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMResources) DeepCopyInto(out *VMResources) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMResources.
func (in *VMResources) DeepCopy() *VMResources {
	if in == nil {
		return nil
	}
	out := new(VMResources)
	in.DeepCopyInto(out)
	return out
}
