apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isolated-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: isolated-pvc
spec:
  runtimeClassName: marooned
  containers:
  - name: box
    image: docker.io/library/busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: isolated-data
