apiVersion: v1
kind: Pod
metadata:
  name: isolated-busybox1
spec:
  runtimeClassName: marooned
  containers:
  - name: box
    image: docker.io/library/busybox:latest
    imagePullPolicy: Always
    command: ["sleep", "3600"]
